/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { Nomenclature } from './nomenclature'

/**
 * Validation of nomenclatures for a survey unit
 */
export type SchemaNomenclature = Nomenclature[]
