/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type { Nomenclature } from './nomenclature'

/**
 * Validation of nomenclatures for a survey unit
 */
export type SchemaNomenclature = Nomenclature[]
