/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.6-SNAPSHOT
 */
import type { StateDataState } from './stateDataState'

export interface StateData {
  /** @minLength 1 */
  currentPage: string
  date: number
  state: StateDataState
}
