/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */
import type { SchemaCollectedData } from '../schema.collected-data/schemaCollectedData'

/**
 * Validation of survey unit data
 */
export interface SchemaData {
  CALCULATED?: unknown
  COLLECTED?: SchemaCollectedData
  EXTERNAL?: unknown
  [key: string]: unknown
}
