/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type { SchemaVariableTypeAnyOfItem } from './schemaVariableTypeAnyOfItem'
import type { SchemaVariableTypeAnyOfTwoItemItem } from './schemaVariableTypeAnyOfTwoItemItem'

/**
 * Validation of variables values in survey unit data
 */
export type SchemaVariableType =
  | string
  | number
  | boolean
  | null
  | SchemaVariableTypeAnyOfItem[]
  | SchemaVariableTypeAnyOfTwoItemItem[][]
