/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { SchemaVariableType } from '../schema.variable-type/schemaVariableType'

export interface CollectedValues {
  COLLECTED?: SchemaVariableType
  EDITED?: SchemaVariableType
  FORCED?: SchemaVariableType
  INPUTED?: SchemaVariableType
  INPUTTED?: SchemaVariableType
  PREVIOUS?: SchemaVariableType
}
