/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */

export type StateDataUpdateState =
  (typeof StateDataUpdateState)[keyof typeof StateDataUpdateState]

export const StateDataUpdateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
