/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { Personalization } from './personalization'

/**
 * Validation of personalizations for a survey unit
 */
export type SchemaPersonalization = Personalization[]
