/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  GetQuestionnaireData200,
  QuestionnaireModelCreation,
  QuestionnaireModelId,
  QuestionnaireModelValue,
  SurveyUnitsOkNok,
} from '../models/api'
import { stromaeInstance } from './axiosInstance'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Search questionnaire ids linked to survey units
 */
export const getQuestionnaireModelIdBySurveyUnits = (
  getQuestionnaireModelIdBySurveyUnitsBody: string[],
  options?: SecondParameter<typeof stromaeInstance>,
) => {
  return stromaeInstance<SurveyUnitsOkNok>(
    {
      url: `/api/survey-units/questionnaire-model-id`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getQuestionnaireModelIdBySurveyUnitsBody,
    },
    options,
  )
}

export const getGetQuestionnaireModelIdBySurveyUnitsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>,
    TError,
    { data: string[] },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>,
  TError,
  { data: string[] },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>,
    { data: string[] }
  > = (props) => {
    const { data } = props ?? {}

    return getQuestionnaireModelIdBySurveyUnits(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetQuestionnaireModelIdBySurveyUnitsMutationResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>
>
export type GetQuestionnaireModelIdBySurveyUnitsMutationBody = string[]
export type GetQuestionnaireModelIdBySurveyUnitsMutationError = unknown

/**
 * @summary Search questionnaire ids linked to survey units
 */
export const useGetQuestionnaireModelIdBySurveyUnits = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>,
    TError,
    { data: string[] },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof getQuestionnaireModelIdBySurveyUnits>>,
  TError,
  { data: string[] },
  TContext
> => {
  const mutationOptions =
    getGetQuestionnaireModelIdBySurveyUnitsMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Create a Questionnaire Model
 */
export const createQuestionnaire = (
  questionnaireModelCreation: QuestionnaireModelCreation,
  options?: SecondParameter<typeof stromaeInstance>,
) => {
  return stromaeInstance<void>(
    {
      url: `/api/questionnaire-models`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: questionnaireModelCreation,
    },
    options,
  )
}

export const getCreateQuestionnaireMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestionnaire>>,
    TError,
    { data: QuestionnaireModelCreation },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createQuestionnaire>>,
  TError,
  { data: QuestionnaireModelCreation },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createQuestionnaire>>,
    { data: QuestionnaireModelCreation }
  > = (props) => {
    const { data } = props ?? {}

    return createQuestionnaire(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateQuestionnaireMutationResult = NonNullable<
  Awaited<ReturnType<typeof createQuestionnaire>>
>
export type CreateQuestionnaireMutationBody = QuestionnaireModelCreation
export type CreateQuestionnaireMutationError = unknown

/**
 * @summary Create a Questionnaire Model
 */
export const useCreateQuestionnaire = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestionnaire>>,
    TError,
    { data: QuestionnaireModelCreation },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof createQuestionnaire>>,
  TError,
  { data: QuestionnaireModelCreation },
  TContext
> => {
  const mutationOptions = getCreateQuestionnaireMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @deprecated
 * @summary Get questionnnaire
 */
export const getQuestionnaireValue = (
  id: string,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<QuestionnaireModelValue>(
    { url: `/api/questionnaire/${id}`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireValueQueryKey = (id: string) => {
  return [`/api/questionnaire/${id}`] as const
}

export const getGetQuestionnaireValueQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireValueQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireValue>>
  > = ({ signal }) => getQuestionnaireValue(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireValue>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetQuestionnaireValueQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireValue>>
>
export type GetQuestionnaireValueQueryError = unknown

export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireValue>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireValue>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @deprecated
 * @summary Get questionnnaire
 */

export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetQuestionnaireValueQueryOptions(id, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @summary Get questionnnaire data
 */
export const getQuestionnaireData = (
  id: string,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<GetQuestionnaireData200>(
    { url: `/api/questionnaire/${id}/data`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireDataQueryKey = (id: string) => {
  return [`/api/questionnaire/${id}/data`] as const
}

export const getGetQuestionnaireDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetQuestionnaireDataQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireData>>
  > = ({ signal }) => getQuestionnaireData(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireData>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetQuestionnaireDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireData>>
>
export type GetQuestionnaireDataQueryError = unknown

export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireData>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireData>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get questionnnaire data
 */

export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetQuestionnaireDataQueryOptions(id, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Get questionnaire list for a campaign
 */
export const getQuestionnaireDatasByCampaignId = (
  id: string,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<QuestionnaireModelValue[]>(
    { url: `/api/campaign/${id}/questionnaires`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireDatasByCampaignIdQueryKey = (id: string) => {
  return [`/api/campaign/${id}/questionnaires`] as const
}

export const getGetQuestionnaireDatasByCampaignIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireDatasByCampaignIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
  > = ({ signal }) =>
    getQuestionnaireDatasByCampaignId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetQuestionnaireDatasByCampaignIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
>
export type GetQuestionnaireDatasByCampaignIdQueryError = unknown

export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get questionnaire list for a campaign
 */

export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetQuestionnaireDatasByCampaignIdQueryOptions(
    id,
    options,
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Get list of questionnaire ids for a campaign
 */
export const getQuestionnaireIdsByCampaignId = (
  id: string,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<QuestionnaireModelId[]>(
    { url: `/api/campaign/${id}/questionnaire-id`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireIdsByCampaignIdQueryKey = (id: string) => {
  return [`/api/campaign/${id}/questionnaire-id`] as const
}

export const getGetQuestionnaireIdsByCampaignIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireIdsByCampaignIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
  > = ({ signal }) =>
    getQuestionnaireIdsByCampaignId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetQuestionnaireIdsByCampaignIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
>
export type GetQuestionnaireIdsByCampaignIdQueryError = unknown

export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get list of questionnaire ids for a campaign
 */

export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetQuestionnaireIdsByCampaignIdQueryOptions(
    id,
    options,
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
