/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import type { SurveyUnitTempZone } from '../models/api'
import type { SchemaSurveyUnitTempZone } from '../models/api/schema.survey-unit-temp-zone'
import { stromaeInstance } from './axiosInstance'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT / INTERVIEWER /
 * @summary Create survey-unit to temp-zone
 */
export const postSurveyUnitByIdInTempZone = (
  id: string,
  schemaSurveyUnitTempZone: SchemaSurveyUnitTempZone,
  options?: SecondParameter<typeof stromaeInstance>,
) => {
  return stromaeInstance<void>(
    {
      url: `/api/survey-unit/${id}/temp-zone`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: schemaSurveyUnitTempZone,
    },
    options,
  )
}

export const getPostSurveyUnitByIdInTempZoneMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>,
    TError,
    { id: string; data: SchemaSurveyUnitTempZone },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>,
  TError,
  { id: string; data: SchemaSurveyUnitTempZone },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>,
    { id: string; data: SchemaSurveyUnitTempZone }
  > = (props) => {
    const { id, data } = props ?? {}

    return postSurveyUnitByIdInTempZone(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostSurveyUnitByIdInTempZoneMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>
>
export type PostSurveyUnitByIdInTempZoneMutationBody = SchemaSurveyUnitTempZone
export type PostSurveyUnitByIdInTempZoneMutationError = unknown

/**
 * @summary Create survey-unit to temp-zone
 */
export const usePostSurveyUnitByIdInTempZone = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>,
    TError,
    { id: string; data: SchemaSurveyUnitTempZone },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postSurveyUnitByIdInTempZone>>,
  TError,
  { id: string; data: SchemaSurveyUnitTempZone },
  TContext
> => {
  const mutationOptions =
    getPostSurveyUnitByIdInTempZoneMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary GET all survey-units in temp-zone
 */
export const getSurveyUnitsInTempZone = (
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<SurveyUnitTempZone[]>(
    { url: `/api/survey-units/temp-zone`, method: 'GET', signal },
    options,
  )
}

export const getGetSurveyUnitsInTempZoneQueryKey = () => {
  return [`/api/survey-units/temp-zone`] as const
}

export const getGetSurveyUnitsInTempZoneQueryOptions = <
  TData = Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof stromaeInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetSurveyUnitsInTempZoneQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>
  > = ({ signal }) => getSurveyUnitsInTempZone(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetSurveyUnitsInTempZoneQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>
>
export type GetSurveyUnitsInTempZoneQueryError = unknown

export function useGetSurveyUnitsInTempZone<
  TData = Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
        TError,
        TData
      >,
      'initialData'
    >
  request?: SecondParameter<typeof stromaeInstance>
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetSurveyUnitsInTempZone<
  TData = Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
        TError,
        TData
      >,
      'initialData'
    >
  request?: SecondParameter<typeof stromaeInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetSurveyUnitsInTempZone<
  TData = Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary GET all survey-units in temp-zone
 */

export function useGetSurveyUnitsInTempZone<
  TData = Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSurveyUnitsInTempZone>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSurveyUnitsInTempZoneQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
