/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { MetadataCreationData } from './metadataCreationData'

export interface CampaignCreationData {
  id?: string
  label: string
  metadata?: MetadataCreationData
  questionnaireIds: string[]
}
