/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateCampaignV2BodyMetadataValueVariablesItemValue } from './createCampaignV2BodyMetadataValueVariablesItemValue'

export type CreateCampaignV2BodyMetadataValueVariablesItem = {
  name: string
  value: CreateCampaignV2BodyMetadataValueVariablesItemValue
}
