/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateUpdateSurveyUnitBodyComment } from './createUpdateSurveyUnitBodyComment'
import type { CreateUpdateSurveyUnitBodyData } from './createUpdateSurveyUnitBodyData'
import type { CreateUpdateSurveyUnitBodyPersonalizationItem } from './createUpdateSurveyUnitBodyPersonalizationItem'
import type { CreateUpdateSurveyUnitBodyStateData } from './createUpdateSurveyUnitBodyStateData'

export type CreateUpdateSurveyUnitBody = {
  comment: CreateUpdateSurveyUnitBodyComment
  /** Validation of survey unit data */
  data: CreateUpdateSurveyUnitBodyData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization: CreateUpdateSurveyUnitBodyPersonalizationItem[]
  questionnaireId: string
  stateData?: CreateUpdateSurveyUnitBodyStateData
}
