/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateCampaignV2BodyMetadataValue } from './createCampaignV2BodyMetadataValue'

export type CreateCampaignV2BodyMetadata = {
  value: CreateCampaignV2BodyMetadataValue
}
