/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateCampaignBodyMetadataValueVariablesItemValue } from './createCampaignBodyMetadataValueVariablesItemValue'

export type CreateCampaignBodyMetadataValueVariablesItem = {
  name: string
  value: CreateCampaignBodyMetadataValueVariablesItemValue
}
