/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateCampaignV2BodyMetadataValueVariablesItem } from './createCampaignV2BodyMetadataValueVariablesItem'

export type CreateCampaignV2BodyMetadataValue = {
  /** @pattern ^(household|business)$ */
  inseeContext?: string
  /** @minItems 0 */
  variables?: CreateCampaignV2BodyMetadataValueVariablesItem[]
  [key: string]: any
}
