/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { CreateCampaignV2BodyMetadata } from './createCampaignV2BodyMetadata'

export type CreateCampaignV2Body = {
  id?: string
  label: string
  metadata?: CreateCampaignV2BodyMetadata
  questionnaireIds: string[]
}
