/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetInterviewerSurveyUnits200ItemDataCOLLECTED } from './getInterviewerSurveyUnits200ItemDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type GetInterviewerSurveyUnits200ItemData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: GetInterviewerSurveyUnits200ItemDataCOLLECTED
  EXTERNAL?: unknown
}
