/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetInterviewerSurveyUnits200ItemStateDataState } from './getInterviewerSurveyUnits200ItemStateDataState'

export type GetInterviewerSurveyUnits200ItemStateData = {
  currentPage?: string
  date?: number
  state?: GetInterviewerSurveyUnits200ItemStateDataState
}
