/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetMetadataByQuestionnaireId200VariablesItemValue } from './getMetadataByQuestionnaireId200VariablesItemValue'

export type GetMetadataByQuestionnaireId200VariablesItem = {
  name: string
  value: GetMetadataByQuestionnaireId200VariablesItemValue
}
