/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetMetadataByCampaignId200VariablesItem } from './getMetadataByCampaignId200VariablesItem'

export type GetMetadataByCampaignId200 = {
  /** @pattern ^(household|business)$ */
  inseeContext?: string
  /** @minItems 0 */
  variables?: GetMetadataByCampaignId200VariablesItem[]
  [key: string]: any
}
