/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetMetadataByCampaignId200VariablesItemValue } from './getMetadataByCampaignId200VariablesItemValue'

export type GetMetadataByCampaignId200VariablesItem = {
  name: string
  value: GetMetadataByCampaignId200VariablesItemValue
}
