/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState'

export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateData = {
  currentPage?: string
  date?: number
  state?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState
}
