/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItem } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItem'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItem } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItem'

export type GetQuestionnaireModelIdBySurveyUnits200 = {
  surveyUnitNOK?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItem[]
  surveyUnitOK?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItem[]
}
