/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireDatasByCampaignId200ItemValue } from './getQuestionnaireDatasByCampaignId200ItemValue'

export type GetQuestionnaireDatasByCampaignId200Item = {
  value?: GetQuestionnaireDatasByCampaignId200ItemValue
}
