/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemComment } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemComment'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemData } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemData'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemPersonalizationItem } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemPersonalizationItem'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateData } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateData'

export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItem = {
  comment?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemComment
  /** Validation of survey unit data */
  data?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemPersonalizationItem[]
  questionnaireId?: string
  stateData?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateData
}
