/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateDataState } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateDataState'

export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateData =
  {
    currentPage?: string
    date?: number
    state?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateDataState
  }
