/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemDataCOLLECTED } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemDataCOLLECTED
  EXTERNAL?: unknown
}
