/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */

export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState =
  (typeof GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState)[keyof typeof GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetQuestionnaireModelIdBySurveyUnits200SurveyUnitOKItemStateDataState =
  {
    INIT: 'INIT',
    COMPLETED: 'COMPLETED',
    VALIDATED: 'VALIDATED',
    TOEXTRACT: 'TOEXTRACT',
    EXTRACTED: 'EXTRACTED',
  } as const
