/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemComment } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemComment'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemData } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemData'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemPersonalizationItem } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemPersonalizationItem'
import type { GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateData } from './getQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateData'

export type GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItem = {
  comment?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemComment
  /** Validation of survey unit data */
  data?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemPersonalizationItem[]
  questionnaireId?: string
  stateData?: GetQuestionnaireModelIdBySurveyUnits200SurveyUnitNOKItemStateData
}
