/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItem } from './getStateDataBySurveyUnits200SurveyUnitNOKItem'
import type { GetStateDataBySurveyUnits200SurveyUnitOKItem } from './getStateDataBySurveyUnits200SurveyUnitOKItem'

export type GetStateDataBySurveyUnits200 = {
  surveyUnitNOK?: GetStateDataBySurveyUnits200SurveyUnitNOKItem[]
  surveyUnitOK?: GetStateDataBySurveyUnits200SurveyUnitOKItem[]
}
