/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitById200StateDataState } from './getSurveyUnitById200StateDataState'

export type GetSurveyUnitById200StateData = {
  currentPage?: string
  date?: number
  state?: GetSurveyUnitById200StateDataState
}
