/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */

export type GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState =
  (typeof GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState)[keyof typeof GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
