/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemDataCOLLECTED } from './getStateDataBySurveyUnits200SurveyUnitOKItemDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type GetStateDataBySurveyUnits200SurveyUnitOKItemData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: GetStateDataBySurveyUnits200SurveyUnitOKItemDataCOLLECTED
  EXTERNAL?: unknown
}
