/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitsInTempZone200ItemSurveyUnit } from './getSurveyUnitsInTempZone200ItemSurveyUnit'

export type GetSurveyUnitsInTempZone200Item = {
  date?: number
  id?: string
  /** Validation of survey unit temp zone */
  surveyUnit?: GetSurveyUnitsInTempZone200ItemSurveyUnit
  surveyUnitId?: string
  userId?: string
}
