/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemStateDataState } from './getStateDataBySurveyUnits200SurveyUnitOKItemStateDataState'

export type GetStateDataBySurveyUnits200SurveyUnitOKItemStateData = {
  currentPage?: string
  date?: number
  state?: GetStateDataBySurveyUnits200SurveyUnitOKItemStateDataState
}
