/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitById200Comment } from './getSurveyUnitById200Comment'
import type { GetSurveyUnitById200Data } from './getSurveyUnitById200Data'
import type { GetSurveyUnitById200PersonalizationItem } from './getSurveyUnitById200PersonalizationItem'
import type { GetSurveyUnitById200StateData } from './getSurveyUnitById200StateData'

export type GetSurveyUnitById200 = {
  comment?: GetSurveyUnitById200Comment
  /** Validation of survey unit data */
  data?: GetSurveyUnitById200Data
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: GetSurveyUnitById200PersonalizationItem[]
  questionnaireId?: string
  stateData?: GetSurveyUnitById200StateData
}
