/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitsInTempZone200ItemSurveyUnitComment } from './getSurveyUnitsInTempZone200ItemSurveyUnitComment'
import type { GetSurveyUnitsInTempZone200ItemSurveyUnitData } from './getSurveyUnitsInTempZone200ItemSurveyUnitData'
import type { GetSurveyUnitsInTempZone200ItemSurveyUnitPersonalizationItem } from './getSurveyUnitsInTempZone200ItemSurveyUnitPersonalizationItem'
import type { GetSurveyUnitsInTempZone200ItemSurveyUnitStateData } from './getSurveyUnitsInTempZone200ItemSurveyUnitStateData'

/**
 * Validation of survey unit temp zone
 */
export type GetSurveyUnitsInTempZone200ItemSurveyUnit = {
  comment?: GetSurveyUnitsInTempZone200ItemSurveyUnitComment
  /** Validation of survey unit data */
  data: GetSurveyUnitsInTempZone200ItemSurveyUnitData
  /** Validation of personalizations for a survey unit */
  personalization?: GetSurveyUnitsInTempZone200ItemSurveyUnitPersonalizationItem[]
  /** @minLength 1 */
  questionnaireId: string
  stateData: GetSurveyUnitsInTempZone200ItemSurveyUnitStateData
}
