/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState } from './getStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState'

export type GetStateDataBySurveyUnits200SurveyUnitNOKItemStateData = {
  currentPage?: string
  date?: number
  state?: GetStateDataBySurveyUnits200SurveyUnitNOKItemStateDataState
}
