/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitById200DataCOLLECTED } from './getSurveyUnitById200DataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type GetSurveyUnitById200Data = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: GetSurveyUnitById200DataCOLLECTED
  EXTERNAL?: unknown
}
