/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemComment } from './getStateDataBySurveyUnits200SurveyUnitOKItemComment'
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemData } from './getStateDataBySurveyUnits200SurveyUnitOKItemData'
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemPersonalizationItem } from './getStateDataBySurveyUnits200SurveyUnitOKItemPersonalizationItem'
import type { GetStateDataBySurveyUnits200SurveyUnitOKItemStateData } from './getStateDataBySurveyUnits200SurveyUnitOKItemStateData'

export type GetStateDataBySurveyUnits200SurveyUnitOKItem = {
  comment?: GetStateDataBySurveyUnits200SurveyUnitOKItemComment
  /** Validation of survey unit data */
  data?: GetStateDataBySurveyUnits200SurveyUnitOKItemData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: GetStateDataBySurveyUnits200SurveyUnitOKItemPersonalizationItem[]
  questionnaireId?: string
  stateData?: GetStateDataBySurveyUnits200SurveyUnitOKItemStateData
}
