/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */

export type GetSurveyUnitsInTempZone200ItemSurveyUnitStateDataState =
  (typeof GetSurveyUnitsInTempZone200ItemSurveyUnitStateDataState)[keyof typeof GetSurveyUnitsInTempZone200ItemSurveyUnitStateDataState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSurveyUnitsInTempZone200ItemSurveyUnitStateDataState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
