/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItemComment } from './getStateDataBySurveyUnits200SurveyUnitNOKItemComment'
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItemData } from './getStateDataBySurveyUnits200SurveyUnitNOKItemData'
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItemPersonalizationItem } from './getStateDataBySurveyUnits200SurveyUnitNOKItemPersonalizationItem'
import type { GetStateDataBySurveyUnits200SurveyUnitNOKItemStateData } from './getStateDataBySurveyUnits200SurveyUnitNOKItemStateData'

export type GetStateDataBySurveyUnits200SurveyUnitNOKItem = {
  comment?: GetStateDataBySurveyUnits200SurveyUnitNOKItemComment
  /** Validation of survey unit data */
  data?: GetStateDataBySurveyUnits200SurveyUnitNOKItemData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: GetStateDataBySurveyUnits200SurveyUnitNOKItemPersonalizationItem[]
  questionnaireId?: string
  stateData?: GetStateDataBySurveyUnits200SurveyUnitNOKItemStateData
}
