/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { GetSurveyUnitsInTempZone200ItemSurveyUnitDataCOLLECTED } from './getSurveyUnitsInTempZone200ItemSurveyUnitDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type GetSurveyUnitsInTempZone200ItemSurveyUnitData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: GetSurveyUnitsInTempZone200ItemSurveyUnitDataCOLLECTED
  EXTERNAL?: unknown
}
