/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */

export type IntegrationResultUnitDtoStatus =
  (typeof IntegrationResultUnitDtoStatus)[keyof typeof IntegrationResultUnitDtoStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationResultUnitDtoStatus = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  ERROR: 'ERROR',
} as const
