/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { IntegrateXmlContext200Campaign } from './integrateXmlContext200Campaign'
import type { IntegrateXmlContext200NomenclaturesItem } from './integrateXmlContext200NomenclaturesItem'
import type { IntegrateXmlContext200QuestionnaireModelsItem } from './integrateXmlContext200QuestionnaireModelsItem'

export type IntegrateXmlContext200 = {
  campaign?: IntegrateXmlContext200Campaign
  nomenclatures?: IntegrateXmlContext200NomenclaturesItem[]
  questionnaireModels?: IntegrateXmlContext200QuestionnaireModelsItem[]
}
