/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { IntegrationResultUnitDtoStatus } from './integrationResultUnitDtoStatus'

export interface IntegrationResultUnitDto {
  cause?: string
  id?: string
  status?: IntegrationResultUnitDtoStatus
}
