/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { IntegrateXmlContext200NomenclaturesItemStatus } from './integrateXmlContext200NomenclaturesItemStatus'

export type IntegrateXmlContext200NomenclaturesItem = {
  cause?: string
  id?: string
  status?: IntegrateXmlContext200NomenclaturesItemStatus
}
