/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { IntegrationResultUnitStatus } from './integrationResultUnitStatus'

export interface IntegrationResultUnit {
  cause?: string
  id?: string
  status?: IntegrationResultUnitStatus
}
