/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */
import type { IntegrationResultUnit } from './integrationResultUnit'

export interface IntegrationResults {
  campaign?: IntegrationResultUnit
  nomenclatures?: IntegrationResultUnit[]
  questionnaireModels?: IntegrationResultUnit[]
}
