/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { IntegrateContext200NomenclaturesItemStatus } from './integrateContext200NomenclaturesItemStatus'

export type IntegrateContext200NomenclaturesItem = {
  cause?: string
  id?: string
  status?: IntegrateContext200NomenclaturesItemStatus
}
