/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { IntegrateXmlContext200CampaignStatus } from './integrateXmlContext200CampaignStatus'

export type IntegrateXmlContext200Campaign = {
  cause?: string
  id?: string
  status?: IntegrateXmlContext200CampaignStatus
}
