/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */

export type IntegrateContext200QuestionnaireModelsItemStatus =
  (typeof IntegrateContext200QuestionnaireModelsItemStatus)[keyof typeof IntegrateContext200QuestionnaireModelsItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrateContext200QuestionnaireModelsItemStatus = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  ERROR: 'ERROR',
} as const
