/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */

export type IntegrateContext200CampaignStatus =
  (typeof IntegrateContext200CampaignStatus)[keyof typeof IntegrateContext200CampaignStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrateContext200CampaignStatus = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  ERROR: 'ERROR',
} as const
