/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type { IntegrationResultUnitStatus } from './integrationResultUnitStatus'

export interface IntegrationResultUnit {
  cause?: string
  id?: string
  status?: IntegrationResultUnitStatus
}
