/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { IntegrationResultUnitDto } from './integrationResultUnitDto'

export interface IntegrationResultsDto {
  campaign?: IntegrationResultUnitDto
  nomenclatures?: IntegrationResultUnitDto[]
  questionnaireModels?: IntegrationResultUnitDto[]
}
