/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { IntegrateContext200QuestionnaireModelsItemStatus } from './integrateContext200QuestionnaireModelsItemStatus'

export type IntegrateContext200QuestionnaireModelsItem = {
  cause?: string
  id?: string
  status?: IntegrateContext200QuestionnaireModelsItemStatus
}
