/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.2-SNAPSHOT
 */
import type { SchemaMetadata } from './schema.metadata/schemaMetadata'

export interface MetadataCreation {
  value: SchemaMetadata
}
