/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { MetadataCreationDataValue } from './metadataCreationDataValue'

export interface MetadataCreationData {
  value: MetadataCreationDataValue
}
