/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { ArrayNode } from './arrayNode'

export interface NomenclatureCreationData {
  id?: string
  label: string
  value: ArrayNode
}
