/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */
import type { SchemaNomenclature } from './schema.nomenclature/schemaNomenclature'

export interface NomenclatureCreation {
  id?: string
  label: string
  value: SchemaNomenclature
}
