/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { PostSurveyUnitByIdInTempZoneBodyComment } from './postSurveyUnitByIdInTempZoneBodyComment'
import type { PostSurveyUnitByIdInTempZoneBodyData } from './postSurveyUnitByIdInTempZoneBodyData'
import type { PostSurveyUnitByIdInTempZoneBodyPersonalizationItem } from './postSurveyUnitByIdInTempZoneBodyPersonalizationItem'
import type { PostSurveyUnitByIdInTempZoneBodyStateData } from './postSurveyUnitByIdInTempZoneBodyStateData'

/**
 * Validation of survey unit temp zone
 */
export type PostSurveyUnitByIdInTempZoneBody = {
  comment?: PostSurveyUnitByIdInTempZoneBodyComment
  /** Validation of survey unit data */
  data: PostSurveyUnitByIdInTempZoneBodyData
  /** Validation of personalizations for a survey unit */
  personalization?: PostSurveyUnitByIdInTempZoneBodyPersonalizationItem[]
  /** @minLength 1 */
  questionnaireId: string
  stateData: PostSurveyUnitByIdInTempZoneBodyStateData
}
