/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { PostNomenclatureBodyValueItem } from './postNomenclatureBodyValueItem'

export type PostNomenclatureBody = {
  id?: string
  label: string
  /** Validation of nomenclatures for a survey unit */
  value: PostNomenclatureBodyValueItem[]
}
