/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */

export type StateDataForSurveyUnitUpdateState =
  (typeof StateDataForSurveyUnitUpdateState)[keyof typeof StateDataForSurveyUnitUpdateState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateDataForSurveyUnitUpdateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
