/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */
import type { StateDataState } from './stateDataState'

export interface StateData {
  currentPage?: string
  date?: number
  state?: StateDataState
}
