/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */

export type StateDataDtoState =
  (typeof StateDataDtoState)[keyof typeof StateDataDtoState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateDataDtoState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
