/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */

export type StateDataInputState =
  (typeof StateDataInputState)[keyof typeof StateDataInputState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateDataInputState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
