/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { StateDataDtoState } from './stateDataDtoState'

export interface StateDataDto {
  currentPage?: string
  date?: number
  state?: StateDataDtoState
}
