/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.15
 */
import type { StateDataForSurveyUnitUpdateState } from './stateDataForSurveyUnitUpdateState'

export interface StateDataForSurveyUnitUpdate {
  currentPage: string
  date: number
  state?: StateDataForSurveyUnitUpdateState
}
