/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */

export type StateDataUpdateState =
  (typeof StateDataUpdateState)[keyof typeof StateDataUpdateState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateDataUpdateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
