/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { StateDataUpdateState } from './stateDataUpdateState'

export interface StateDataUpdate {
  currentPage: string
  date: number
  state: StateDataUpdateState
}
