/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */

export type SurveyUnitMetadataContext =
  (typeof SurveyUnitMetadataContext)[keyof typeof SurveyUnitMetadataContext]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SurveyUnitMetadataContext = {
  household: 'household',
  business: 'business',
} as const
