/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.2-SNAPSHOT
 */
import type { SurveyUnitUpdateComment } from './surveyUnitUpdateComment'
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateDataUpdate } from './stateDataUpdate'

export interface SurveyUnitUpdate {
  comment?: SurveyUnitUpdateComment
  data?: SchemaData
  personalization?: SchemaPersonalization
  stateData?: StateDataUpdate
}
