/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */

export type SurveyUnitDataStateDataUpdateInputData = { [key: string]: any }
