/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitCreationComment } from './surveyUnitCreationComment'
import type { SurveyUnitCreationData } from './surveyUnitCreationData'
import type { SurveyUnitCreationPersonalizationItem } from './surveyUnitCreationPersonalizationItem'
import type { SurveyUnitCreationStateData } from './surveyUnitCreationStateData'

export interface SurveyUnitCreation {
  comment: SurveyUnitCreationComment
  /** Validation of survey unit data */
  data: SurveyUnitCreationData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization: SurveyUnitCreationPersonalizationItem[]
  questionnaireId: string
  stateData?: SurveyUnitCreationStateData
}
