/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { SchemaSurveyUnitTempZone } from './schema.survey-unit-temp-zone/schemaSurveyUnitTempZone'

export interface SurveyUnitTempZone {
  date?: number
  id?: string
  surveyUnit?: SchemaSurveyUnitTempZone
  surveyUnitId?: string
  userId?: string
}
