/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { StateDataDto } from './stateDataDto'

export interface SurveyUnitDto {
  comment?: string
  data?: string
  id?: string
  personalization?: string
  questionnaireId?: string
  stateData?: StateDataDto
}
