/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitCreationComment } from './surveyUnitCreationComment'
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateDataUpdate } from './stateDataUpdate'

export interface SurveyUnitCreation {
  comment: SurveyUnitCreationComment
  data: SchemaData
  id?: string
  personalization: SchemaPersonalization
  questionnaireId: string
  stateData?: StateDataUpdate
}
