/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitUpdateDataCOLLECTED } from './surveyUnitUpdateDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type SurveyUnitUpdateData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: SurveyUnitUpdateDataCOLLECTED
  EXTERNAL?: unknown
}
