/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { SurveyUnitUpdateInputComment } from './surveyUnitUpdateInputComment'
import type { SurveyUnitUpdateInputData } from './surveyUnitUpdateInputData'
import type { ArrayNode } from './arrayNode'
import type { StateDataInput } from './stateDataInput'

export interface SurveyUnitUpdateInput {
  comment?: SurveyUnitUpdateInputComment
  data?: SurveyUnitUpdateInputData
  personalization?: ArrayNode
  stateData?: StateDataInput
}
