/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitsOkNokSurveyUnitNOKItemComment } from './surveyUnitsOkNokSurveyUnitNOKItemComment'
import type { SurveyUnitsOkNokSurveyUnitNOKItemData } from './surveyUnitsOkNokSurveyUnitNOKItemData'
import type { SurveyUnitsOkNokSurveyUnitNOKItemPersonalizationItem } from './surveyUnitsOkNokSurveyUnitNOKItemPersonalizationItem'
import type { SurveyUnitsOkNokSurveyUnitNOKItemStateData } from './surveyUnitsOkNokSurveyUnitNOKItemStateData'

export type SurveyUnitsOkNokSurveyUnitNOKItem = {
  comment?: SurveyUnitsOkNokSurveyUnitNOKItemComment
  /** Validation of survey unit data */
  data?: SurveyUnitsOkNokSurveyUnitNOKItemData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: SurveyUnitsOkNokSurveyUnitNOKItemPersonalizationItem[]
  questionnaireId?: string
  stateData?: SurveyUnitsOkNokSurveyUnitNOKItemStateData
}
