/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitTempZoneSurveyUnit } from './surveyUnitTempZoneSurveyUnit'

export interface SurveyUnitTempZone {
  date?: number
  id?: string
  /** Validation of survey unit temp zone */
  surveyUnit?: SurveyUnitTempZoneSurveyUnit
  surveyUnitId?: string
  userId?: string
}
