/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.10-SNAPSHOT
 */
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateDataUpdate } from './stateDataUpdate'
import type { SurveyUnitUpdateComment } from './surveyUnitUpdateComment'

export interface SurveyUnitUpdate {
  comment?: SurveyUnitUpdateComment
  data?: SchemaData
  personalization?: SchemaPersonalization
  stateData?: StateDataUpdate
}
