/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitsOkNokSurveyUnitNOKItem } from './surveyUnitsOkNokSurveyUnitNOKItem'
import type { SurveyUnitsOkNokSurveyUnitOKItem } from './surveyUnitsOkNokSurveyUnitOKItem'

export interface SurveyUnitsOkNok {
  surveyUnitNOK?: SurveyUnitsOkNokSurveyUnitNOKItem[]
  surveyUnitOK?: SurveyUnitsOkNokSurveyUnitOKItem[]
}
