/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.4-SNAPSHOT
 */
import type { SchemaCollectedData } from './schema.collected-data/schemaCollectedData'
import type { StateDataUpdate } from './stateDataUpdate'

export interface SurveyUnitDataStateDataUpdate {
  data?: SchemaCollectedData
  stateData: StateDataUpdate
}
