/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { SurveyUnitComment } from './surveyUnitComment'
import type { SurveyUnitData } from './surveyUnitData'
import type { SurveyUnitPersonalizationItem } from './surveyUnitPersonalizationItem'
import type { SurveyUnitStateData } from './surveyUnitStateData'

export interface SurveyUnit {
  comment?: SurveyUnitComment
  /** Validation of survey unit data */
  data?: SurveyUnitData
  id?: string
  /** Validation of personalizations for a survey unit */
  personalization?: SurveyUnitPersonalizationItem[]
  questionnaireId?: string
  stateData?: SurveyUnitStateData
}
