/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * queen-application
 * API for Queen/Stromae
 * OpenAPI spec version: 4.2.1
 */
import type { ArrayNode } from './arrayNode'
import type { StateDataInput } from './stateDataInput'
import type { SurveyUnitCreationInputComment } from './surveyUnitCreationInputComment'
import type { SurveyUnitCreationInputData } from './surveyUnitCreationInputData'

export interface SurveyUnitCreationInput {
  comment: SurveyUnitCreationInputComment
  data: SurveyUnitCreationInputData
  id?: string
  personalization: ArrayNode
  questionnaireId: string
  stateData?: StateDataInput
}
