/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { UpdateSurveyUnitByIdBodyDataCOLLECTED } from './updateSurveyUnitByIdBodyDataCOLLECTED'

/**
 * Validation of survey unit data
 */
export type UpdateSurveyUnitByIdBodyData = {
  CALCULATED?: unknown
  /** Validation of survey unit collected data */
  COLLECTED?: UpdateSurveyUnitByIdBodyDataCOLLECTED
  EXTERNAL?: unknown
}
