/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { UpdateSurveyUnitDataStateDataByIdBodyData } from './updateSurveyUnitDataStateDataByIdBodyData'
import type { UpdateSurveyUnitDataStateDataByIdBodyStateData } from './updateSurveyUnitDataStateDataByIdBodyStateData'

export type UpdateSurveyUnitDataStateDataByIdBody = {
  /** Validation of survey unit collected data */
  data: UpdateSurveyUnitDataStateDataByIdBodyData
  stateData: UpdateSurveyUnitDataStateDataByIdBodyStateData
}
