/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.8-SNAPSHOT
 */
import type { SchemaMetadataInseeContext } from './schemaMetadataInseeContext'
import type { Variable } from './variable'

export interface SchemaMetadata {
  inseeContext?: SchemaMetadataInseeContext
  /** @minItems 0 */
  variables?: Variable[]
  [key: string]: any
}
