/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.1-SNAPSHOT
 */
import type { Variable } from './variable'

export interface SchemaMetadata {
  /** @pattern ^(household|business)$ */
  inseeContext?: string
  /** @minItems 0 */
  variables?: Variable[]
  [key: string]: any
}
