/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 4.3.6-SNAPSHOT
 */

export type SchemaMetadataInseeContext =
  (typeof SchemaMetadataInseeContext)[keyof typeof SchemaMetadataInseeContext]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaMetadataInseeContext = {
  household: 'household',
  business: 'business',
} as const
